### ISSUE TITLE
Adding episodes

### ISSUE THREAD

**Issue by orchid00** [LibraryCarpentry/Top10FAIR#1]
Hi I'll be happy to help adding episodes when the 10 "things" are ready!

**Comment by libcce** [comment]
Thanks @orchid00 !

**Comment by mkuzak** [comment]
Hi @orchid00 I have added software things to the episodes. Currently plain md. Next step will be to migrate it to lesson template.

**Comment by orchid00** [comment]
1. will each of those 10 things file become a lesson with 10 episodes?
2. or each 10 things will be one episode of a big lesson?

**Comment by mkuzak** [comment]
currently there is only one repository for all, so I would expect option 1. At the same time option 2 makes more sense. Curious what @libcce had in mind.

**Comment by orchid00** [comment]
@mkuzak I think you got my two options backwards, but happy to wait for @libcce to move on.

**Comment by libcce** [comment]
hi @orchid00 @mkuzak orginal idea was to have each top 10 things resource to be an episode in one lesson. there is something wrong, where the episodes are not showing up on the lesson table of contents, well, one of them should be showing up, the introduction. i've asked @fmichonneau what might be happening. but yes, we will have to add headers to the things like you see in the introduction. plus, we will probably have to wrangle with the formatting a bit more, to mirror Carpentries lesson episodes. maybe we can start with the biodiversity episode to settle on the format we will be using for the others.

**Comment by libcce** [comment]
thanks @fmichonneau just saw that you added some missing files to help with displaying the episodes on the table of contents.

**Comment by orchid00** [comment]
yay! http://librarycarpentry.org/Top10FAIR/Bio-diversity_Top10-FAIR-Things/index.html I'll add titles!

**Comment by mkuzak** [comment]
yes, in fact I did :)

**Comment by libcce** [comment]
@mkuzak @orchid00 what file naming do you want to use for the episodes? right now the introduction follows the right format, to start off with the episode number then the title. my first take would be to rename the software episode to 03-software.md but we might want to include the full name, so 03-top10-fair-data-things-software.md or flip it around to 03-software-top10-fair-data-things.md. i think like the latter?

**Comment by mkuzak** [comment]
+1 for  03-software.md

**Comment by orchid00** [comment]
I'll also go for shorter names

**Comment by orchid00** [comment]
yes, I'll close
