### ISSUE TITLE
Formatting questions

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/Top10FAIR#5]
Hi @orchid00, I'm going to make some formatting changes to the lesson and wanted to check with you (and others) first:

- I'm going to remove the teaching and exercise times since we didn't discuss this in the sprint. I'll also remove the questions and objectives in the overview section and include the sprinters, audience, and description instead (in the overview callout). I'll also remove the key points callout.

- On the table of contents page, I'll change the formatting so that it only lists the titles of the Things, the sprinters.

- For the Things exercises, I'm thinking we will use the .discussion special blockquotes callout. 

Is there anything else you think we should change regarding the formatting?

**Comment by orchid00** [comment]
Hi Chris @libcce,

Thanks for your message. I think the yml heading is part of the template, and I am afraid that if you remove it it will break the rendering. 
Also letting you know that Key questions go to the main page: http://librarycarpentry.org/Top10FAIR/ and the reference: http://librarycarpentry.org/Top10FAIR/reference.html
I would also suggest to keep key points which are like a summary at the end of each episode (green box) that could be a list of the 10 things per topic.

If you have already tried in your local and it works without the heading, then I think your formatting suggestions are good!

other than that for formatting I will suggest

heading 1 title
no heading for sprinters
and a paragraph of description
then heading 2 for each "Thing"

**Comment by libcce** [comment]
@orchid00 had some more time to think about this and it seems like hacking The Carpentries lesson template might not be the best way to go. Bookdown might be better suited for something like this https://bookdown.org/yihui/bookdown-demo/. One big reason I'm asking this is that occasionally we update the lesson repos and if we have a hacked repo, then it cause issues further down the road. What do you think? I've never used Bookdown before but I believe @jt14den has or maybe you have used it?

**Comment by orchid00** [comment]
Yeah you might need to pick one option! :gear: 
I've used bookdown, not have had any problems with it, so far but neither have had too much to deal with it.
There's also gitbooks and read the docs, these three options work well with markdown. Then you might need to pick a template that suits your needs. 
At the moment, I would be happy to help you maintain the site, whatever template you are using, I can find my way around. I should clarify that i am not going to help setting up the site because of lack of time. 
Also, please note that on the 19th of dec I might suddenly be eaten by earth (i'm going on holidays). :tada:

**Comment by mkuzak** [comment]
I'm in favour of choosing a book format for this content (gitbook or bookdown). This will fit much better. I've heard good things about bookdown and I have used gitbook a bit, both should do the job.

**Comment by libcce** [comment]
Hi @mkuzak @orchid00 I found a simple theme to use https://libcce.github.io/Top-10-FAIR/ What do you think? I can move this repo to the LC org if you like it? From there we can use something like pandoc or similar to produce the PDF for Zenodo.

**Comment by orchid00** [comment]
hi @libcce it looks nice, I like it. 
Question, is it possible to add a menu to the right side? to add mobility between things.

**Comment by libcce** [comment]
Yes, that's one thing I will need to do is add some navigational links @orchid00 but that should be simple.

**Comment by mkuzak** [comment]
@libcce looks good, I like it

**Comment by libcce** [comment]
We are using https://github.com/LibraryCarpentry/Top-10-FAIR now.
